### ISSUE TITLE
Random shattered sound when playing tinyplay WAV file

### ISSUE THREAD

**Issue by di0x7c5** [bringmeup/hub#15]
Sometimes (once per ten) after play WAV file by `tinyplay` the sound is shattered. Needs further investigation.

**Comment by di0x7c5** [comment]
When shutter sound occurring `dmesg` spits with below message:
```
max98090 2-0010: PLL unlocked
max98090 2-0010: PLL unlocked
max98090 2-0010: PLL unlocked
max98090 2-0010: PLL unlocked
max98090 2-0010: PLL unlocked
max98090 2-0010: PLL unlocked
max98090 2-0010: PLL unlocked
```

**Comment by nazgee** [comment]
blue - bottom side of PCB, easy to access
red - top, under the heatsink, hard to access

![audio-i2s](https://user-images.githubusercontent.com/1335286/37963883-ed5bd560-31bf-11e8-9a0e-53d370000cd1.png)

**Comment by nazgee** [comment]
![dsc_4561](https://user-images.githubusercontent.com/1335286/38104806-a6d192ca-338a-11e8-97f9-cc61e4a07b7f.JPG)

12MHz != 24MHz :D

**Comment by nazgee** [comment]
dts:
```
		clocks = <&clks IMX6QDL_CLK_CKO>;
		clock-names = "mclk";
```

actual clocks setup:
```
 osc                                      6            6    24000000          0 0  
    cko2_sel                              1            1    24000000          0 0  
       cko2_podf                          1            1    24000000          0 0  
          cko2                            1            1    24000000          0 0  
             cko                          1            1    24000000          0 0  
```

**Comment by nazgee** [comment]
fixed by https://github.com/bringmeup/linux-imx6/commit/cd26d074e9477a150e810b45b8651adb799d9054
